name: regaderazo
description: an app for our proyect.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  bloc:
  flutter_bloc:
  # Widgets
  cupertino_icons:
  syncfusion_flutter_charts:
  font_awesome_flutter:
  sleek_circular_slider:
  audioplayers:
  # Firebase
  firebase_core: 
  firebase_auth: 
  cloud_firestore: 
  firebase_ui_firestore:
  flutterfire_ui:
  # Google
  google_sign_in: 
  share_plus: 
  equatable:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: 
  
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/regaderazo_sin.png
    - assets/regaderazo_logo.png
    - assets/time.mp3
  
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
