name: regaderazo
description: an app for our proyect.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  bloc: ^8.1.0
  flutter_bloc: ^8.1.1
  # Widgets
  cupertino_icons: ^1.0.2
  syncfusion_flutter_charts: ^20.3.52
  font_awesome_flutter: ^10.2.1
  # Firebase
  firebase_core: ^2.1.0
  firebase_auth: ^4.0.2
  cloud_firestore: ^4.0.2
  firebase_ui_firestore: ^1.0.2
  # Google
  google_sign_in: ^5.4.2
  share_plus: ^6.1.0
  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/regaderazo_sin.png
    - assets/regaderazo_logo.png
  
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
